name: Deploy Grafana to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: velvety-accord-387513
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        export_default_credentials: true
    
    - name: Install gke-gcloud-auth-plugin
      run: gcloud components install gke-gcloud-auth-plugin
      

    - name: Authenticate to GKE
      run: |
        gcloud container clusters get-credentials cluster-2 --zone us-central1-c

    - name: Deploy Grafana
      run: |
        kubectl apply -f kubernetes/Grafana_Dep.yml
        kubectl apply -f kubernetes/Grafana_Svc.yml
